version: '3.8'

services:
    web:
        build: . 
        restart: always
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        ports:
            - 8000:8000
    nginx:
        build: ./nginx
        restart: always
        ports:
         - 1300:80
        depends_on:
          - web
          



  



 
